export const initialTools = [
  {
    id: 'ALT-001',
    name: 'Total Station',
    image: '/images/total-station.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-002',
    name: 'GPS Geodetik',
    image: '/images/gps-geodetik.png',
    type: 'Elektronik',
    status: 'Dipinjam',
    condition: 'Baik',
  },
  {
    id: 'ALT-003',
    name: 'Waterpass',
    image: '/images/waterpass.png',
    type: 'Optik',
    status: 'Tersedia',
    condition: 'Perbaikan',
  },
  {
    id: 'ALT-004',
    name: 'Theodolite',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-005',
    name: 'Digital Theodolite',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-006',
    name: 'Automatic Level',
    image: '/images/placeholder-64x64.png',
    type: 'Optik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-007',
    name: 'Laser Scanner',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Dipinjam',
    condition: 'Baik',
  },
  {
    id: 'ALT-008',
    name: 'Drone RTK',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-009',
    name: 'Prisma Polygon',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-010',
    name: 'Rambu Ukur',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Perbaikan',
  },
  {
    id: 'ALT-011',
    name: 'Tripod',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-012',
    name: 'Pita Ukur',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Dipinjam',
    condition: 'Baik',
  },
  {
    id: 'ALT-013',
    name: 'Kompas',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-014',
    name: 'Palu Geologi',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Tersedia',
    condition: 'Baik',
  },
];
