export const initialTools = [
  {
    id: 'ALT-001',
    name: 'GPS GEODETIC -  TYPE : CHC',
    image: '/images/alat1.jpg',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-002',
    name: 'GPS GEODETIC - TYPE : SOUTH',
    image: '/images/alat2.jpg',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-003',
    name: 'GPS GEODETIC - TYPE : COMNAV',
    image: '/images/alat3.jpg',
    type: 'Optik',
    status: 'Tersedia',
    condition: 'Perbaikan',
  },
  {
    id: 'ALT-004',
    name: 'GPS GEODETIC - TYPE : HORIZON',
    image: '/images/alat4.jpg',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-005',
    name: 'CONTROLLER - TYPE : CHC',
    image: '/images/alat5.jpg',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-006',
    name: 'TRIBACH - TYPE : CHC , HORIZON',
    image: '/images/alat6.jpg',
    type: 'Optik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-007',
    name: 'Laser Scanner',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-008',
    name: 'Drone RTK',
    image: '/images/placeholder-64x64.png',
    type: 'Elektronik',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-009',
    name: 'Prisma Polygon',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-010',
    name: 'Rambu Ukur',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Perbaikan',
  },
  {
    id: 'ALT-011',
    name: 'Tripod',
    image: '/images/placeholder-64x64.png',
    type: 'Aksesoris',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-012',
    name: 'Pita Ukur',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-013',
    name: 'Kompas',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Tersedia',
    condition: 'Baik',
  },
  {
    id: 'ALT-014',
    name: 'Palu Geologi',
    image: '/images/placeholder-64x64.png',
    type: 'Manual',
    status: 'Tersedia',
    condition: 'Baik',
  },
];
